### ISSUE TITLE
Kartan mobiiliparannus

### ISSUE THREAD

**Issue by Excaa** [wappuradio/webbi2019#65]
Karttanäkymä paremmaksi mobiililla. Nykyisellään vaikeasti luettava.

**Comment by xaaria** [comment]
![Screenshot_2024-03-19-19-31-10-82_3aea4af51f236e4932235fdada7d1643](https://github.com/wappuradio/webbi2019/assets/5833555/4b6f58ba-006a-4bb7-b37b-2b4dd16e61ba)

Firefox, Android
