### ISSUE TITLE
Yläpalkin mobiilinäkymän parantaminen

### ISSUE THREAD

**Issue by Excaa** [wappuradio/webbi2019#66]
Nykysivulla yläpalkki kroppaa mobiililla.
![image](https://github.com/wappuradio/webbi2019/assets/5547994/e598cda3-bb2a-4bd2-8211-95f7550a6a55)

Triviaali korjausehdotus (muutama css-fiksi):
![image](https://github.com/wappuradio/webbi2019/assets/5547994/b09d1f24-e933-45cc-9ad3-1767f0e63a50)

**Comment by xaaria** [comment]
Yksi mitä olen töissä tehnyt pari kertaa on, että logot tms. korvaa **ikonilla** kapeilla näytöillä. 

Some-riville voisi laittaa `justify-content: center;` tai left
